### PR TITLE
Added Screener Function

### PR DESCRIPTION
**Pull request by MikeThomasMakes**
Added screener function in endpoints.py.
My changes to client.py are meaningless I think. Just a few removed spaces. Can be ignored.

Conditions parameter must be sent as a string according to Intrinio syntax here:
http://docs.intrinio.com/#securities-search-screener

Not sure if I'm contributing this code to your branch correctly. I'm not a frequent github user.
Please correct anything I'm doing wrong.

### CODE REVIEW

**Comment by nhedlund** [comment]
Thanks for contributing, I will take a look as soon as I can.

Do I understand correctly that it is the screener function that you want to add and that the other changes are not necessary?

**Comment by MikeThomasMakes** [comment]
Yes. I thought I made changes to client.py, but I'm pretty sure the
screener is self contained in endpoint.py.

Let me know what you think. Would love to develop this further and optimize
the screener to reduce tickers found. Max conditions is 10, based on
intrinio limitations. They plan to increase.

**Comment by nhedlund** [comment]
Now I got to look at the screener function, it looks good. Is it ok if I add the screener function directly instead of merging this PR? I think that would be easier.

I will do some minor changes and add a test as well.

**Comment by MikeThomasMakes** [comment]
Really? Awesome! Whatever you think is best. I'm not a strong github user.

Cool. Can you let me know how it turns out?

On Jan 29, 2018 3:21 PM, "nhedlund" <notifications@github.com> wrote:

Now I got to look at the screener function, it looks good. Is it ok if I
add the screener function directly instead of merging this PR? I think that
would be easier.

I will do some minor changes and add a test as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nhedlund/intrinio/pull/8#issuecomment-361373682>, or mute
the thread

**Comment by nhedlund** [comment]
Now it is live in version 0.2.0! I added the screener to the docs as well.

Made all the parameters optional except for the conditions parameter.

**Comment by MikeThomasMakes** [comment]
Awesome! Thanks for adding it.

**Pull request closed without merging**
